/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.57 from the
 * contents of GTKWin.xs. Do not edit this file, edit GTKWin.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "./GTKWin.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include <gtk/gtk.h>
#include <pcap.h>

#ifdef __linux__
#include <pcap/sll.h>
#endif

#include <stdio.h>
#include <string.h>
#include <arpa/inet.h>
#include <netinet/ip.h>
#include <netinet/udp.h>
#include <net/ethernet.h>

typedef struct {
    SV *from;
    SV *to;
} BindingUserdata;

static gboolean
sv_to_gvalue(SV *sv, GValue *value)
{
    if (G_VALUE_HOLDS_BOOLEAN(value)) {
        g_value_set_boolean(value, SvTRUE(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_CHAR(value)) {
        g_value_set_schar(value, (gchar)SvIV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_UCHAR(value)) {
        g_value_set_uchar(value, (guchar)SvUV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_INT(value)) {
        g_value_set_int(value, (gint)SvIV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_UINT(value)) {
        g_value_set_uint(value, (guint)SvUV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_LONG(value)) {
        g_value_set_long(value, (glong)SvIV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_ULONG(value)) {
        g_value_set_ulong(value, (gulong)SvUV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_INT64(value)) {
        g_value_set_int64(value, (gint64)SvIV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_UINT64(value)) {
        g_value_set_uint64(value, (guint64)SvUV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_FLOAT(value)) {
        g_value_set_float(value, (gfloat)SvNV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_DOUBLE(value)) {
        g_value_set_double(value, SvNV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_STRING(value)) {
        if (SvOK(sv)) {
            STRLEN len;
            const gchar *str = SvPVutf8(sv, len);
            g_value_set_string(value, str);
        } else {
            g_value_set_string(value, NULL);
        }

        return TRUE;
    }

    if (G_VALUE_HOLDS_ENUM(value)) {
        g_value_set_enum(value, (gint)SvIV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_FLAGS(value)) {
        g_value_set_flags(value, (guint)SvUV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_GTYPE(value)) {
        g_value_set_gtype(value, (GType)SvUV(sv));
        return TRUE;
    }

    if (G_VALUE_HOLDS_OBJECT(value)) {
        if (!SvOK(sv)) {
            g_value_set_object(value, NULL);
            return TRUE;
        }

        if (!sv_isobject(sv))
            croak("Expected G::Object object");

        IV iv = SvIV(SvRV(sv));
        GObject *obj = INT2PTR(GObject *, iv);

        if (!G_IS_OBJECT(obj))
            croak("Invalid GObject pointer");

        if (!G_TYPE_CHECK_INSTANCE_TYPE(obj, G_VALUE_TYPE(value)))
            croak("Expected object of type %s",
                  g_type_name(G_VALUE_TYPE(value)));

        g_value_set_object(value, obj);
        return TRUE;
    }

    croak("Unsupported GValue type '%s'",
          g_type_name(G_VALUE_TYPE(value)));

    return FALSE;
}

static SV *
gvalue_to_sv(const GValue *value)
{
    if (G_VALUE_HOLDS_BOOLEAN(value))
        return newSViv(g_value_get_boolean(value));

    if (G_VALUE_HOLDS_CHAR(value))
        return newSViv(g_value_get_schar(value));

    if (G_VALUE_HOLDS_UCHAR(value))
        return newSVuv(g_value_get_uchar(value));

    if (G_VALUE_HOLDS_INT(value))
        return newSViv(g_value_get_int(value));

    if (G_VALUE_HOLDS_UINT(value))
        return newSVuv(g_value_get_uint(value));

    if (G_VALUE_HOLDS_LONG(value))
        return newSViv(g_value_get_long(value));

    if (G_VALUE_HOLDS_ULONG(value))
        return newSVuv(g_value_get_ulong(value));

    if (G_VALUE_HOLDS_INT64(value))
        return newSViv(g_value_get_int64(value));

    if (G_VALUE_HOLDS_UINT64(value))
        return newSVuv(g_value_get_uint64(value));

    if (G_VALUE_HOLDS_FLOAT(value))
        return newSVnv(g_value_get_float(value));

    if (G_VALUE_HOLDS_DOUBLE(value))
        return newSVnv(g_value_get_double(value));

    if (G_VALUE_HOLDS_STRING(value)) {
        const gchar *s = g_value_get_string(value);

        if (!s)
            return newSV(0);

        SV *sv = newSVpv(s, 0);
        SvUTF8_on(sv);
        return sv;
    }

    if (G_VALUE_HOLDS_ENUM(value))
        return newSViv(g_value_get_enum(value));

    if (G_VALUE_HOLDS_FLAGS(value))
        return newSVuv(g_value_get_flags(value));

    if (G_VALUE_HOLDS_GTYPE(value))
        return newSVuv(g_value_get_gtype(value));

    if (G_VALUE_HOLDS_OBJECT(value)) {
        GObject *obj = g_value_get_object(value);

        if (!obj)
            return newSV(0);

        SV *sv = newSV(0);
        sv_setref_pv(sv, "G::Object", obj);

        return sv;
    }

    croak("Unsupported GValue type '%s'",
          g_type_name(G_VALUE_TYPE(value)));
}

typedef struct {
    SV *callback;
    int datalink;
} PCAPContext;

typedef struct
{
    char src_ip[INET_ADDRSTRLEN];
    char dst_ip[INET_ADDRSTRLEN];

    unsigned short src_port;
    unsigned short dst_port;

    unsigned char src_mac[6];
    unsigned char dst_mac[6];

    const unsigned char *payload;
    int payload_len;

} UDPPacketInfo;

#include "typedefs.h"

static int
parse_udp_packet(const unsigned char *packet,
                 int datalink,
                 int packet_len,
                 UDPPacketInfo *info)
{
    const struct ether_header *eth;
    const struct ip *ip;
    const struct udphdr *udp;

    int offset = 0;


    if (packet_len < sizeof(struct ether_header))
        return 0;


    switch (datalink) {

    case DLT_RAW:
        offset = 0;
        break;

    case DLT_NULL:
    case DLT_LOOP:
        offset = sizeof(uint32_t);
        break;

    case DLT_EN10MB:
        offset = sizeof(struct ether_header);
        break;

    #ifdef DLT_LINUX_SLL
    case DLT_LINUX_SLL:
        offset = sizeof(struct sll_header);
        break;
    #endif

    default:
        return 0;
    }

    if (packet_len < offset) {
        return 0;
    }

    ip = (const struct ip *)(packet + offset);


    if (ip->ip_p != IPPROTO_UDP)
        return 0;


    inet_ntop(AF_INET,
              &ip->ip_src,
              info->src_ip,
              sizeof(info->src_ip));

    inet_ntop(AF_INET,
              &ip->ip_dst,
              info->dst_ip,
              sizeof(info->dst_ip));


    offset += ip->ip_hl * 4;


    if (packet_len < offset + sizeof(struct udphdr))
        return 0;


    udp = (const struct udphdr *)(packet + offset);


    info->src_port = ntohs(udp->uh_sport);
    info->dst_port = ntohs(udp->uh_dport);


    offset += sizeof(struct udphdr);


    info->payload = packet + offset;

    info->payload_len =
        packet_len - offset;


    return 1;
}

static void
gtk_win_pcap_handler(u_char *userdata,
             const struct pcap_pkthdr *header,
             const u_char *packet)
{
    PCAPContext *ctx = (PCAPContext *)userdata;
    SV *callback = ctx->callback;
    int datalink = ctx->datalink;
    dSP;

    UDPPacketInfo *udp_packet_info;

    Newxz(udp_packet_info, 1, UDPPacketInfo);

    parse_udp_packet(packet, datalink, header->caplen, udp_packet_info);

    ENTER;
    SAVETMPS;

    PUSHMARK(SP);

    XPUSHs(sv_2mortal(
        sv_setref_pv(newSV(0),
                     "PCAP::Packet",
                     (void *)udp_packet_info)
    ));

    PUTBACK;

    SvREFCNT_inc(callback);
    call_sv(callback, G_DISCARD);

    FREETMPS;
    LEAVE;
}

static gboolean
binding_callback(GBinding     *binding,
                      const GValue *from_value,
                      GValue       *to_value,
                      SV *callback)
{
    if (!SvOK(callback)) {
        return FALSE;
    }
    gboolean handled = FALSE;

    dSP;

    ENTER;
    SAVETMPS;

    PUSHMARK(SP);

    XPUSHs(sv_2mortal(gvalue_to_sv(from_value)));

    PUTBACK;

    int count = call_sv(callback, G_SCALAR | G_EVAL);

    SPAGAIN;

    if (SvTRUE(ERRSV)) {
        Perl_warn("Perl binding callback failed: %s",
             SvPV_nolen(ERRSV));

        sv_setsv(ERRSV, &PL_sv_undef);
        count = 0;
    }

    if (count >= 1) {
        SV *ret = POPs;

        handled = sv_to_gvalue(ret, to_value);
    }

    PUTBACK;

    FREETMPS;
    LEAVE;

    return handled;
}

static gboolean
binding_callback_from(GBinding *binding,
    const GValue *from_value,
    GValue *to_value,
    gpointer user_data) {
    BindingUserdata *binding_data = (BindingUserdata *) user_data;
    SV *callback = binding_data->from;
    return binding_callback(binding, from_value, to_value, callback);
}
static gboolean
binding_callback_to(GBinding *binding,
    const GValue *from_value,
    GValue *to_value,
    gpointer user_data) {
    BindingUserdata *binding_data = (BindingUserdata *) user_data;
    SV *callback = binding_data->to;
    return binding_callback(binding, from_value, to_value, callback);
}

static void
perl_signal_callback(GObject *object, gpointer data)
{
    SV *callback = (SV *)data;
    dSP;

    ENTER;
    SAVETMPS;

    PUSHMARK(SP);

    XPUSHs(sv_2mortal(newSViv(PTR2IV(object))));
    PUTBACK;

    call_sv(callback, G_DISCARD);

    FREETMPS;
    LEAVE;
}


#line 456 "./GTKWin.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

/* simple backcompat versions of the TARGx() macros with no optimisation */
#ifndef TARGi
#  define TARGi(iv, do_taint) sv_setiv_mg(TARG, iv)
#  define TARGu(uv, do_taint) sv_setuv_mg(TARG, uv)
#  define TARGn(nv, do_taint) sv_setnv_mg(TARG, nv)
#endif

#line 607 "./GTKWin.c"

XS_EUPXS(XS_Gtk__Overlay_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Overlay_new)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	Gtk__Overlay	RETVAL;
#line 451 "./GTKWin.xs"
        RETVAL = GTK_OVERLAY (gtk_overlay_new());
        g_object_ref_sink(G_OBJECT (RETVAL));
#line 620 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::Overlay", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Overlay_add_overlay); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Overlay_add_overlay)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "over, child");
    {
	Gtk__Overlay	over;
	GtkWidget *	child;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_overlay_get_type())) {
                over = GTK_OVERLAY (gobject);
            } else {
                croak("Not implementing GTK_OVERLAY");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Overlay object");
    }
;

    if (sv_isobject(ST(1))) {
        IV integer_pointer = SvIV(SvRV(ST(1)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_widget_get_type())) {
                child = GTK_WIDGET (gobject);
            } else {
                croak("Not implementing GTK_WIDGET");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Widget object");
    }
;
#line 459 "./GTKWin.xs"
        gtk_overlay_add_overlay(over, child);
#line 679 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Overlay_set_child); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Overlay_set_child)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "over, child");
    {
	Gtk__Overlay	over;
	GtkWidget *	child;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_overlay_get_type())) {
                over = GTK_OVERLAY (gobject);
            } else {
                croak("Not implementing GTK_OVERLAY");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Overlay object");
    }
;

    if (sv_isobject(ST(1))) {
        IV integer_pointer = SvIV(SvRV(ST(1)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_widget_get_type())) {
                child = GTK_WIDGET (gobject);
            } else {
                croak("Not implementing GTK_WIDGET");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Widget object");
    }
;
#line 464 "./GTKWin.xs"
        gtk_overlay_set_child(over, child);
#line 732 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Grid_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Grid_new)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	Gtk__Grid	RETVAL;
#line 471 "./GTKWin.xs"
        RETVAL = GTK_GRID (gtk_grid_new());
        g_object_ref_sink(RETVAL);
#line 749 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::Grid", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Grid_attach); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Grid_attach)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "self, widget, column, row, width, height");
    {
	Gtk__Grid	self;
	Gtk__Widget	widget;
	int	column = (int)SvIV(ST(2))
;
	int	row = (int)SvIV(ST(3))
;
	int	width = (int)SvIV(ST(4))
;
	int	height = (int)SvIV(ST(5))
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_grid_get_type())) {
                self = GTK_GRID (gobject);
            } else {
                croak("Not implementing GTK_GRID");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Grid object");
    }
;

    if (sv_isobject(ST(1))) {
        IV integer_pointer = SvIV(SvRV(ST(1)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_widget_get_type())) {
                widget = GTK_WIDGET (gobject);
            } else {
                croak("Not implementing GTK_WIDGET");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Widget object");
    }
;
#line 479 "./GTKWin.xs"
        gtk_grid_attach(self, widget, column, row, width, height);
#line 816 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Label_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Label_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, label");
    {
	Gtk__Label	RETVAL;
	SV *	class = ST(0)
;
	char *	label = (char *)SvPV_nolen(ST(1))
;
#line 486 "./GTKWin.xs"
        RETVAL = GTK_LABEL (gtk_label_new((char *)label));
        g_object_ref_sink(RETVAL);
#line 837 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::Label", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


/* INCLUDE:  Including 'Constants.xsi' from 'GTKWin.xs' */


XS_EUPXS(XS_Gtk__Win__Constants_GTK_ALIGN_FILL); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_GTK_ALIGN_FILL)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	unsigned int	RETVAL;
	dXSTARG;
#line 6 "./Constants.xsi"
    RETVAL = (unsigned int) GTK_ALIGN_FILL;
#line 863 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Win__Constants_GTK_ALIGN_START); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_GTK_ALIGN_START)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	unsigned int	RETVAL;
	dXSTARG;
#line 13 "./Constants.xsi"
    RETVAL = (unsigned int) GTK_ALIGN_START;
#line 882 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Win__Constants_GTK_ALIGN_END); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_GTK_ALIGN_END)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	unsigned int	RETVAL;
	dXSTARG;
#line 20 "./Constants.xsi"
    RETVAL = (unsigned int) GTK_ALIGN_END;
#line 901 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Win__Constants_GTK_ALIGN_CENTER); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_GTK_ALIGN_CENTER)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	unsigned int	RETVAL;
	dXSTARG;
#line 27 "./Constants.xsi"
    RETVAL = (unsigned int) GTK_ALIGN_CENTER;
#line 920 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Win__Constants_GTK_ORIENTATION_VERTICAL); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_GTK_ORIENTATION_VERTICAL)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	unsigned int	RETVAL;
	dXSTARG;
#line 34 "./Constants.xsi"
    RETVAL = (unsigned int) GTK_ORIENTATION_VERTICAL;
#line 939 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Win__Constants_GTK_STYLE_PROVIDER_PRIORITY_APPLICATION); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_GTK_STYLE_PROVIDER_PRIORITY_APPLICATION)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	unsigned int	RETVAL;
	dXSTARG;
#line 41 "./Constants.xsi"
    RETVAL = (unsigned int) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION;
#line 958 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Win__Constants_G_BINDING_SYNC_CREATE); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_G_BINDING_SYNC_CREATE)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	unsigned int	RETVAL;
	dXSTARG;
#line 48 "./Constants.xsi"
    RETVAL = (unsigned int) G_BINDING_SYNC_CREATE;
#line 977 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Win__Constants_G_BINDING_DEFAULT); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_G_BINDING_DEFAULT)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	unsigned int	RETVAL;
	dXSTARG;
#line 55 "./Constants.xsi"
    RETVAL = (unsigned int) G_BINDING_DEFAULT;
#line 996 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Win__Constants_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_new)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	Gtk__Win__Constants	RETVAL;
#line 62 "./Constants.xsi"
        RETVAL = malloc(sizeof *RETVAL);
        *RETVAL = 1;
#line 1015 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	    sv_setref_pv(RETVALSV, "Gtk::Win::Constants", (void*)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Win__Constants_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Win__Constants_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	Gtk__Win__Constants	self;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(Gtk__Win__Constants,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"Gtk::Win::Constants::DESTROY",
			"self")
;
#line 70 "./Constants.xsi"
        free(self);
#line 1047 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


/* INCLUDE: Returning to 'GTKWin.xs' from 'Constants.xsi' */


XS_EUPXS(XS_Gtk__ApplicationWindow_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__ApplicationWindow_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, app");
    {
	Gtk__ApplicationWindow	RETVAL;
	SV *	class = ST(0)
;
	Gtk__Application	app;

    if (sv_isobject(ST(1))) {
        IV integer_pointer = SvIV(SvRV(ST(1)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_application_get_type())) {
                app = GTK_APPLICATION (gobject);
            } else {
                croak("Not implementing GTK_APPLICATION");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Application object");
    }
;
#line 498 "./GTKWin.xs"
        RETVAL = GTK_APPLICATION_WINDOW (gtk_application_window_new(app));
        g_object_ref_sink(G_OBJECT (RETVAL));
#line 1088 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::ApplicationWindow", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__Packet_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Packet_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "packet");
    {
	PCAP__Packet	packet;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    packet = INT2PTR(PCAP__Packet,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"PCAP::Packet::DESTROY",
			"packet")
;
#line 508 "./GTKWin.xs"
        Safefree(packet);
#line 1120 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_PCAP__Packet_src_ip); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Packet_src_ip)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "packet");
    {
	char *	RETVAL;
	dXSTARG;
	PCAP__Packet	packet;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Packet")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    packet = INT2PTR(PCAP__Packet,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Packet::src_ip",
			"packet", "PCAP::Packet",
			refstr, ST(0)
		);
	}
;
#line 513 "./GTKWin.xs"
        RETVAL = packet->src_ip;
#line 1152 "./GTKWin.c"
	sv_setpv((SV*)TARG, RETVAL);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__Packet_dst_ip); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Packet_dst_ip)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "packet");
    {
	char *	RETVAL;
	dXSTARG;
	PCAP__Packet	packet;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Packet")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    packet = INT2PTR(PCAP__Packet,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Packet::dst_ip",
			"packet", "PCAP::Packet",
			refstr, ST(0)
		);
	}
;
#line 520 "./GTKWin.xs"
        RETVAL = packet->dst_ip;
#line 1186 "./GTKWin.c"
	sv_setpv((SV*)TARG, RETVAL);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__Packet_src_port); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Packet_src_port)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "packet");
    {
	unsigned short	RETVAL;
	dXSTARG;
	PCAP__Packet	packet;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Packet")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    packet = INT2PTR(PCAP__Packet,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Packet::src_port",
			"packet", "PCAP::Packet",
			refstr, ST(0)
		);
	}
;
#line 527 "./GTKWin.xs"
        RETVAL = packet->src_port;
#line 1220 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__Packet_dst_port); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Packet_dst_port)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "packet");
    {
	unsigned short	RETVAL;
	dXSTARG;
	PCAP__Packet	packet;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Packet")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    packet = INT2PTR(PCAP__Packet,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Packet::dst_port",
			"packet", "PCAP::Packet",
			refstr, ST(0)
		);
	}
;
#line 534 "./GTKWin.xs"
        RETVAL = packet->dst_port;
#line 1254 "./GTKWin.c"
	TARGu((UV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__Packet_payload); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Packet_payload)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "packet");
    {
	SV *	RETVAL;
	PCAP__Packet	packet;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Packet")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    packet = INT2PTR(PCAP__Packet,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Packet::payload",
			"packet", "PCAP::Packet",
			refstr, ST(0)
		);
	}
;
#line 541 "./GTKWin.xs"
        RETVAL = newSVpv(packet->payload, (STRLEN) packet->payload_len);
#line 1287 "./GTKWin.c"
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__Program_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Program_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	PCAP__Program	self;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(PCAP__Program,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"PCAP::Program::DESTROY",
			"self")
;
#line 550 "./GTKWin.xs"
        pcap_freecode(self);
        free(self);
#line 1316 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_PCAP__Handle_datalink); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Handle_datalink)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	int	RETVAL;
	dXSTARG;
	PCAP__Handle	self;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Handle")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(PCAP__Handle,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Handle::datalink",
			"self", "PCAP::Handle",
			refstr, ST(0)
		);
	}
;
#line 558 "./GTKWin.xs"
        RETVAL = pcap_datalink(self);
#line 1348 "./GTKWin.c"
	TARGi((IV)RETVAL, 1);
	ST(0) = TARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__Handle_compile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Handle_compile)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "self, program, optimize");
    {
	PCAP__Program	RETVAL;
	PCAP__Handle	self;
	unsigned char *	program = (unsigned char *)SvPV_nolen(ST(1))
;
	int	optimize = (int)SvIV(ST(2))
;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Handle")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(PCAP__Handle,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Handle::compile",
			"self", "PCAP::Handle",
			refstr, ST(0)
		);
	}
;
#line 565 "./GTKWin.xs"
        RETVAL = malloc(sizeof *RETVAL);
        if (pcap_compile(self, RETVAL, program, optimize, PCAP_NETMASK_UNKNOWN) == -1) {
            Perl_croak("%s", pcap_geterr(self));
        }
#line 1388 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	    sv_setref_pv(RETVALSV, "PCAP::Program", (void*)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__Handle_set_filter); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Handle_set_filter)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, program");
    {
	PCAP__Handle	self;
	PCAP__Program	program;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Handle")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(PCAP__Handle,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Handle::set_filter",
			"self", "PCAP::Handle",
			refstr, ST(0)
		);
	}
;

	if (SvROK(ST(1)) && sv_derived_from(ST(1), "PCAP::Program")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    program = INT2PTR(PCAP__Program,tmp);
	}
	else {
		const char* refstr = SvROK(ST(1)) ? "" : SvOK(ST(1)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Handle::set_filter",
			"program", "PCAP::Program",
			refstr, ST(1)
		);
	}
;
#line 575 "./GTKWin.xs"
        if (pcap_setfilter(self, program) == -1) {
            Perl_croak("%s", pcap_geterr(self));
        }
#line 1441 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_PCAP__Handle_set_direction); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Handle_set_direction)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, direction");
    {
	PCAP__Handle	self;
	unsigned char *	direction = (unsigned char *)SvPV_nolen(ST(1))
;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Handle")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(PCAP__Handle,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Handle::set_direction",
			"self", "PCAP::Handle",
			refstr, ST(0)
		);
	}
;
#line 582 "./GTKWin.xs"
        if (0 != strcmp(direction, "out")) {
            Perl_croak("Direction not supported");
        }
        pcap_setdirection(self, PCAP_D_OUT);
#line 1476 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_PCAP__Handle_loop); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Handle_loop)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, coderef");
    {
	PCAP__Handle	self;
	SV *	coderef = ST(1)
;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::Handle")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(PCAP__Handle,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::Handle::loop",
			"self", "PCAP::Handle",
			refstr, ST(0)
		);
	}
;
#line 590 "./GTKWin.xs"
        if (!SvROK(coderef) ||
            SvTYPE(SvRV(coderef)) != SVt_PVCV)
        {
            Perl_croak(aTHX_ "loop() requires a CODE reference");
        }
        PCAPContext *ctx = malloc(sizeof(*ctx));
        ctx->callback = coderef;
        ctx->datalink = pcap_datalink(self);

        pcap_loop(self, -1, gtk_win_pcap_handler, (u_char *)ctx);
        free(ctx);
#line 1518 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_PCAP__Handle_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__Handle_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	PCAP__Handle	self;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(PCAP__Handle,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"PCAP::Handle::DESTROY",
			"self")
;
#line 605 "./GTKWin.xs"
        pcap_close(self);
#line 1544 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_PCAP__If_find_all_devs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__If_find_all_devs)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	PCAP__If	RETVAL;
#line 612 "./GTKWin.xs"
        char errbuf[PCAP_ERRBUF_SIZE];
        if (pcap_findalldevs(&RETVAL, errbuf) == -1) {
            Perl_croak("%s", errbuf);
        }
#line 1563 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	    sv_setref_pv(RETVALSV, "PCAP::If", (void*)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__If_open_live); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__If_open_live)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "self, listen_addr, snaplen, promisc, to_ms");
    {
	PCAP__Handle	RETVAL;
	PCAP__If	self;
	char *	listen_addr = (char *)SvPV_nolen(ST(1))
;
	int	snaplen = (int)SvIV(ST(2))
;
	int	promisc = (int)SvIV(ST(3))
;
	int	to_ms = (int)SvIV(ST(4))
;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "PCAP::If")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(PCAP__If,tmp);
	}
	else {
		const char* refstr = SvROK(ST(0)) ? "" : SvOK(ST(0)) ? "scalar " : "undef";
	    Perl_croak_nocontext("%s: Expected %s to be of type %s; got %s%" SVf " instead",
			"PCAP::If::open_live",
			"self", "PCAP::If",
			refstr, ST(0)
		);
	}
;
#line 622 "./GTKWin.xs"
        char errbuf[PCAP_ERRBUF_SIZE];
        pcap_if_t *dev = NULL;
        for (dev = self; dev; dev = dev->next) {
            pcap_addr_t *addr;
            if (dev->flags & PCAP_IF_LOOPBACK)
                continue;
            for (addr = dev->addresses; addr; addr = addr->next) {
                struct sockaddr_in *sin;
                if (addr->addr == NULL)
                    continue;
                if (addr->addr->sa_family != AF_INET)
                    continue;
                sin = (struct sockaddr_in *)addr->addr;
                if (strcmp(inet_ntoa(sin->sin_addr), listen_addr) == 0)
                    goto found;
            }
        }
        dev = NULL;
        found:
        if (dev == NULL) {
            Perl_croak("Interface not found");
        }
        RETVAL = pcap_open_live(dev->name, snaplen, promisc, to_ms, errbuf);
        if (RETVAL == NULL) {
            Perl_croak("%s", errbuf);
        }
#line 1633 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	    sv_setref_pv(RETVALSV, "PCAP::Handle", (void*)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_PCAP__If_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_PCAP__If_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "self");
    {
	PCAP__If	self;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    self = INT2PTR(PCAP__If,tmp);
	}
	else
	    Perl_croak_nocontext("%s: %s is not a reference",
			"PCAP::If::DESTROY",
			"self")
;
#line 654 "./GTKWin.xs"
        pcap_freealldevs(self);
#line 1665 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Entry_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Entry_new)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	Gtk__Entry	RETVAL;
#line 661 "./GTKWin.xs"
        RETVAL = GTK_ENTRY (gtk_entry_new());
        g_object_ref_sink(G_OBJECT (RETVAL));
#line 1682 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::Entry", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__CheckButton_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__CheckButton_new)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	Gtk__CheckButton	RETVAL;
#line 671 "./GTKWin.xs"
        RETVAL = GTK_CHECK_BUTTON (gtk_check_button_new());
        g_object_ref_sink(G_OBJECT (RETVAL));
#line 1705 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::CheckButton", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Button_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Button_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, label");
    {
	Gtk__Button	RETVAL;
	SV *	class = ST(0)
;
	char *	label = (char *)SvPV_nolen(ST(1))
;
#line 681 "./GTKWin.xs"
        RETVAL = GTK_BUTTON (gtk_button_new_with_label(label));
        g_object_ref_sink(G_OBJECT (RETVAL));
#line 1732 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::Button", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Window_set_title); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Window_set_title)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, title");
    {
	Gtk__Window	self;
	char *	title = (char *)SvPV_nolen(ST(1))
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_window_get_type())) {
                self = GTK_WINDOW (gobject);
            } else {
                croak("Not implementing GTK_WINDOW");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Window object");
    }
;
#line 691 "./GTKWin.xs"
        gtk_window_set_title(self, title);
#line 1774 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Window_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Window_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	Gtk__Window	RETVAL;
	SV *	class = ST(0)
;
#line 696 "./GTKWin.xs"
        RETVAL = GTK_WINDOW (gtk_window_new());
        g_object_ref_sink(G_OBJECT (RETVAL));
#line 1793 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::Window", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Window_set_default_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Window_set_default_size)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "win, width, height");
    {
	Gtk__Window	win;
	int	width = (int)SvIV(ST(1))
;
	int	height = (int)SvIV(ST(2))
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_window_get_type())) {
                win = GTK_WINDOW (gobject);
            } else {
                croak("Not implementing GTK_WINDOW");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Window object");
    }
;
#line 704 "./GTKWin.xs"
        gtk_window_set_default_size(win, width, height);
#line 1837 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Window_set_resizable); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Window_set_resizable)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "win, resizable");
    {
	Gtk__Window	win;
	int	resizable = (int)SvIV(ST(1))
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_window_get_type())) {
                win = GTK_WINDOW (gobject);
            } else {
                croak("Not implementing GTK_WINDOW");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Window object");
    }
;
#line 709 "./GTKWin.xs"
        gtk_window_set_resizable(win, !!resizable);
#line 1873 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Window_set_child); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Window_set_child)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "win, child");
    {
	Gtk__Window	win;
	GtkWidget *	child;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_window_get_type())) {
                win = GTK_WINDOW (gobject);
            } else {
                croak("Not implementing GTK_WINDOW");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Window object");
    }
;

    if (sv_isobject(ST(1))) {
        IV integer_pointer = SvIV(SvRV(ST(1)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_widget_get_type())) {
                child = GTK_WIDGET (gobject);
            } else {
                croak("Not implementing GTK_WIDGET");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Widget object");
    }
;
#line 714 "./GTKWin.xs"
        gtk_window_set_child(win, child);
#line 1926 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Window_present); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Window_present)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "win");
    {
	Gtk__Window	win;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_window_get_type())) {
                win = GTK_WINDOW (gobject);
            } else {
                croak("Not implementing GTK_WINDOW");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Window object");
    }
;
#line 719 "./GTKWin.xs"
        gtk_window_present(win);
#line 1960 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Box_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Box_new)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "class, orientation, spacing");
    {
	Gtk__Box	RETVAL;
	SV *	class = ST(0)
;
	unsigned int	orientation = (unsigned int)SvUV(ST(1))
;
	int	spacing = (int)SvIV(ST(2))
;
#line 726 "./GTKWin.xs"
        RETVAL = GTK_BOX (gtk_box_new(orientation, spacing));
        g_object_ref_sink(RETVAL);
#line 1983 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::Box", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Widget_add_css_class); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Widget_add_css_class)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "widget, class");
    {
	Gtk__Widget	widget;
	char *	class = (char *)SvPV_nolen(ST(1))
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_widget_get_type())) {
                widget = GTK_WIDGET (gobject);
            } else {
                croak("Not implementing GTK_WIDGET");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Widget object");
    }
;
#line 736 "./GTKWin.xs"
        gtk_widget_add_css_class(widget, class);
#line 2025 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Widget_get_display); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Widget_get_display)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "widget");
    {
	Gdk__Display	RETVAL;
	Gtk__Widget	widget;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_widget_get_type())) {
                widget = GTK_WIDGET (gobject);
            } else {
                croak("Not implementing GTK_WIDGET");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Widget object");
    }
;
#line 741 "./GTKWin.xs"
        RETVAL = gtk_widget_get_display(widget);
        g_object_ref_sink(RETVAL);
#line 2061 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gdk::Display", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Widget_set_valign); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Widget_set_valign)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "widget, constant");
    {
	Gtk__Widget	widget;
	unsigned int	constant = (unsigned int)SvUV(ST(1))
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_widget_get_type())) {
                widget = GTK_WIDGET (gobject);
            } else {
                croak("Not implementing GTK_WIDGET");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Widget object");
    }
;
#line 749 "./GTKWin.xs"
        gtk_widget_set_valign(widget, constant);
#line 2103 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Widget_set_halign); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Widget_set_halign)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "widget, constant");
    {
	Gtk__Widget	widget;
	unsigned int	constant = (unsigned int)SvUV(ST(1))
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_widget_get_type())) {
                widget = GTK_WIDGET (gobject);
            } else {
                croak("Not implementing GTK_WIDGET");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::Widget object");
    }
;
#line 754 "./GTKWin.xs"
        gtk_widget_set_halign(widget, constant);
#line 2139 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gtk__Application_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Application_new)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "class, app_name, flags");
    {
	Gtk__Application	RETVAL;
	SV *	class = ST(0)
;
	char *	app_name = (char *)SvPV_nolen(ST(1))
;
	size_t	flags = (size_t)SvUV(ST(2))
;
#line 761 "./GTKWin.xs"
        RETVAL = GTK_APPLICATION (gtk_application_new(app_name, flags));
        g_object_ref_sink(G_OBJECT (RETVAL));
#line 2162 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::Application", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gio__Application_run); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gio__Application_run)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "app, ...");
    {
	Gio__Application	app;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, g_application_get_type())) {
                app = G_APPLICATION (gobject);
            } else {
                croak("Not implementing G_APPLICATION");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gio::Application object");
    }
;
#line 771 "./GTKWin.xs"
        int argc = items - 1;
        char **argv = malloc((argc + 1) * sizeof(*argv));

        argv[0] = "app";

        for (int i = 1; i < argc; i++) {
            argv[i] = SvPV_nolen(ST(i));
        }

        argv[argc] = NULL;

        g_application_run(app, argc, argv);

        free(argv);
#line 2215 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gio__File_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gio__File_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, path");
    {
	Gio__File	RETVAL;
	SV *	class = ST(0)
;
	unsigned char *	path = (unsigned char *)SvPV_nolen(ST(1))
;
#line 791 "./GTKWin.xs"
        RETVAL = g_file_new_for_path(path);
        g_object_ref_sink(RETVAL);
#line 2236 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gio::File", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__Picture_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__Picture_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, texture");
    {
	Gtk__Picture	RETVAL;
	SV *	class = ST(0)
;
	Gdk__Texture	texture;

    if (sv_isobject(ST(1))) {
        IV integer_pointer = SvIV(SvRV(ST(1)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gdk_texture_get_type())) {
                texture = GDK_TEXTURE (gobject);
            } else {
                croak("Not implementing GDK_TEXTURE");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gdk::Texture object");
    }
;
#line 801 "./GTKWin.xs"
        RETVAL = GTK_PICTURE (gtk_picture_new_for_paintable(GDK_PAINTABLE (texture)));
        g_object_ref_sink(RETVAL);
#line 2280 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::Picture", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__CssProvider_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__CssProvider_new)
{
    dVAR; dXSARGS;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
	Gtk__CssProvider	RETVAL;
#line 811 "./GTKWin.xs"
        RETVAL =  gtk_css_provider_new();
        g_object_ref_sink(RETVAL);
#line 2303 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gtk::CssProvider", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Gtk__CssProvider_load_from_path); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gtk__CssProvider_load_from_path)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "self, path");
    {
	Gtk__CssProvider	self;
	char *	path = (char *)SvPV_nolen(ST(1))
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_css_provider_get_type())) {
                self = GTK_CSS_PROVIDER (gobject);
            } else {
                croak("Not implementing GTK_CSS_PROVIDER");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::CssProvider object");
    }
;
#line 819 "./GTKWin.xs"
        gtk_css_provider_load_from_path(self, path);
#line 2345 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gdk__Display_add_css_provider); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gdk__Display_add_css_provider)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "self, provider, priority");
    {
	Gdk__Display	self;
	Gtk__CssProvider	provider;
	int	priority = (int)SvIV(ST(2))
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gdk_display_get_type())) {
                self = GDK_DISPLAY (gobject);
            } else {
                croak("Not implementing GDK_DISPLAY");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gdk::Display object");
    }
;

    if (sv_isobject(ST(1))) {
        IV integer_pointer = SvIV(SvRV(ST(1)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, gtk_css_provider_get_type())) {
                provider = GTK_CSS_PROVIDER (gobject);
            } else {
                croak("Not implementing GTK_CSS_PROVIDER");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gtk::CssProvider object");
    }
;
#line 826 "./GTKWin.xs"
        gtk_style_context_add_provider_for_display(self, GTK_STYLE_PROVIDER (provider), priority);
#line 2400 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Gdk__Texture_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Gdk__Texture_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "class, file");
    {
	Gdk__Texture	RETVAL;
	SV *	class = ST(0)
;
	Gio__File	file;

    if (sv_isobject(ST(1))) {
        IV integer_pointer = SvIV(SvRV(ST(1)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, g_file_get_type())) {
                file = G_FILE (gobject);
            } else {
                croak("Not implementing G_FILE");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected Gio::File object");
    }
;
#line 833 "./GTKWin.xs"
        GError *error = NULL;
        RETVAL = gdk_texture_new_from_file(file, &error);
        g_object_ref_sink(RETVAL);
        if (error != NULL) {
            Perl_croak(error->message);
        }
#line 2442 "./GTKWin.c"
	{
	    SV * RETVALSV;
	    RETVALSV = sv_newmortal();
	sv_setref_pv(RETVALSV, "Gdk::Texture", (void *)RETVAL);
	    ST(0) = RETVALSV;
	}
    }
    XSRETURN(1);
}


XS_EUPXS(XS_G__Object_bind_property_full); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_G__Object_bind_property_full)
{
    dVAR; dXSARGS;
    if (items != 7)
       croak_xs_usage(cv,  "self, self_property, target, target_property, flags, transform_to, transform_from");
    {
	G__Object	self;
	char *	self_property = (char *)SvPV_nolen(ST(1))
;
	G__Object	target;
	char *	target_property = (char *)SvPV_nolen(ST(3))
;
	int	flags = (int)SvIV(ST(4))
;
	SV *	transform_to = ST(5)
;
	SV *	transform_from = ST(6)
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, g_object_get_type())) {
                self = G_OBJECT (gobject);
            } else {
                croak("Not implementing G_OBJECT");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected G::Object object");
    }
;

    if (sv_isobject(ST(2))) {
        IV integer_pointer = SvIV(SvRV(ST(2)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, g_object_get_type())) {
                target = G_OBJECT (gobject);
            } else {
                croak("Not implementing G_OBJECT");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected G::Object object");
    }
;
#line 847 "./GTKWin.xs"
        BindingUserdata *userdata = malloc(sizeof *userdata);
        SvREFCNT_inc(transform_to);
        SvREFCNT_inc(transform_from);
        userdata->to = transform_to;
        userdata->from = transform_from;
        g_object_bind_property_full(self, self_property, target, target_property, flags, binding_callback_to, binding_callback_from, userdata, NULL);
#line 2516 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_G__Object_connect); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_G__Object_connect)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "obj, signal, callback");
    {
	G__Object	obj;
	SV *	signal = ST(1)
;
	SV *	callback = ST(2)
;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, g_object_get_type())) {
                obj = G_OBJECT (gobject);
            } else {
                croak("Not implementing G_OBJECT");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected G::Object object");
    }
;
#line 858 "./GTKWin.xs"
        if (!SvROK(callback) || SvTYPE(SvRV(callback)) != SVt_PVCV) {
            croak("callback must be a coderef");
        }

        SvREFCNT_inc(callback);

        g_signal_connect(
            obj,
            SvPV_nolen(signal),
            G_CALLBACK(perl_signal_callback),
            callback
        );
#line 2565 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_G__Object_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_G__Object_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    {
	G__Object	obj;

    if (sv_isobject(ST(0))) {
        IV integer_pointer = SvIV(SvRV(ST(0)));
        void *void_object = INT2PTR(void *, integer_pointer);
        if (G_IS_OBJECT(void_object)) {
            GObject *gobject = G_OBJECT (void_object);
            if (G_TYPE_CHECK_INSTANCE_TYPE(gobject, g_object_get_type())) {
                obj = G_OBJECT (gobject);
            } else {
                croak("Not implementing G_OBJECT");
            }
        } else {
            croak("Expected gobject");
        }
    } else {
        croak("Expected G::Object object");
    }
;
#line 874 "./GTKWin.xs"
        if (obj) {
            g_object_unref(obj);
        }
#line 2601 "./GTKWin.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C" {
#endif
XS_EXTERNAL(boot_GTKWin); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_GTKWin)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Gtk::Overlay::new", XS_Gtk__Overlay_new);
        newXS_deffile("Gtk::Overlay::add_overlay", XS_Gtk__Overlay_add_overlay);
        newXS_deffile("Gtk::Overlay::set_child", XS_Gtk__Overlay_set_child);
        newXS_deffile("Gtk::Grid::new", XS_Gtk__Grid_new);
        newXS_deffile("Gtk::Grid::attach", XS_Gtk__Grid_attach);
        newXS_deffile("Gtk::Label::new", XS_Gtk__Label_new);
        newXS_deffile("Gtk::Win::Constants::GTK_ALIGN_FILL", XS_Gtk__Win__Constants_GTK_ALIGN_FILL);
        newXS_deffile("Gtk::Win::Constants::GTK_ALIGN_START", XS_Gtk__Win__Constants_GTK_ALIGN_START);
        newXS_deffile("Gtk::Win::Constants::GTK_ALIGN_END", XS_Gtk__Win__Constants_GTK_ALIGN_END);
        newXS_deffile("Gtk::Win::Constants::GTK_ALIGN_CENTER", XS_Gtk__Win__Constants_GTK_ALIGN_CENTER);
        newXS_deffile("Gtk::Win::Constants::GTK_ORIENTATION_VERTICAL", XS_Gtk__Win__Constants_GTK_ORIENTATION_VERTICAL);
        newXS_deffile("Gtk::Win::Constants::GTK_STYLE_PROVIDER_PRIORITY_APPLICATION", XS_Gtk__Win__Constants_GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
        newXS_deffile("Gtk::Win::Constants::G_BINDING_SYNC_CREATE", XS_Gtk__Win__Constants_G_BINDING_SYNC_CREATE);
        newXS_deffile("Gtk::Win::Constants::G_BINDING_DEFAULT", XS_Gtk__Win__Constants_G_BINDING_DEFAULT);
        newXS_deffile("Gtk::Win::Constants::new", XS_Gtk__Win__Constants_new);
        newXS_deffile("Gtk::Win::Constants::DESTROY", XS_Gtk__Win__Constants_DESTROY);
        newXS_deffile("Gtk::ApplicationWindow::new", XS_Gtk__ApplicationWindow_new);
        newXS_deffile("PCAP::Packet::DESTROY", XS_PCAP__Packet_DESTROY);
        newXS_deffile("PCAP::Packet::src_ip", XS_PCAP__Packet_src_ip);
        newXS_deffile("PCAP::Packet::dst_ip", XS_PCAP__Packet_dst_ip);
        newXS_deffile("PCAP::Packet::src_port", XS_PCAP__Packet_src_port);
        newXS_deffile("PCAP::Packet::dst_port", XS_PCAP__Packet_dst_port);
        newXS_deffile("PCAP::Packet::payload", XS_PCAP__Packet_payload);
        newXS_deffile("PCAP::Program::DESTROY", XS_PCAP__Program_DESTROY);
        newXS_deffile("PCAP::Handle::datalink", XS_PCAP__Handle_datalink);
        newXS_deffile("PCAP::Handle::compile", XS_PCAP__Handle_compile);
        newXS_deffile("PCAP::Handle::set_filter", XS_PCAP__Handle_set_filter);
        newXS_deffile("PCAP::Handle::set_direction", XS_PCAP__Handle_set_direction);
        newXS_deffile("PCAP::Handle::loop", XS_PCAP__Handle_loop);
        newXS_deffile("PCAP::Handle::DESTROY", XS_PCAP__Handle_DESTROY);
        newXS_deffile("PCAP::If::find_all_devs", XS_PCAP__If_find_all_devs);
        newXS_deffile("PCAP::If::open_live", XS_PCAP__If_open_live);
        newXS_deffile("PCAP::If::DESTROY", XS_PCAP__If_DESTROY);
        newXS_deffile("Gtk::Entry::new", XS_Gtk__Entry_new);
        newXS_deffile("Gtk::CheckButton::new", XS_Gtk__CheckButton_new);
        newXS_deffile("Gtk::Button::new", XS_Gtk__Button_new);
        newXS_deffile("Gtk::Window::set_title", XS_Gtk__Window_set_title);
        newXS_deffile("Gtk::Window::new", XS_Gtk__Window_new);
        newXS_deffile("Gtk::Window::set_default_size", XS_Gtk__Window_set_default_size);
        newXS_deffile("Gtk::Window::set_resizable", XS_Gtk__Window_set_resizable);
        newXS_deffile("Gtk::Window::set_child", XS_Gtk__Window_set_child);
        newXS_deffile("Gtk::Window::present", XS_Gtk__Window_present);
        newXS_deffile("Gtk::Box::new", XS_Gtk__Box_new);
        newXS_deffile("Gtk::Widget::add_css_class", XS_Gtk__Widget_add_css_class);
        newXS_deffile("Gtk::Widget::get_display", XS_Gtk__Widget_get_display);
        newXS_deffile("Gtk::Widget::set_valign", XS_Gtk__Widget_set_valign);
        newXS_deffile("Gtk::Widget::set_halign", XS_Gtk__Widget_set_halign);
        newXS_deffile("Gtk::Application::new", XS_Gtk__Application_new);
        newXS_deffile("Gio::Application::run", XS_Gio__Application_run);
        newXS_deffile("Gio::File::new", XS_Gio__File_new);
        newXS_deffile("Gtk::Picture::new", XS_Gtk__Picture_new);
        newXS_deffile("Gtk::CssProvider::new", XS_Gtk__CssProvider_new);
        newXS_deffile("Gtk::CssProvider::load_from_path", XS_Gtk__CssProvider_load_from_path);
        newXS_deffile("Gdk::Display::add_css_provider", XS_Gdk__Display_add_css_provider);
        newXS_deffile("Gdk::Texture::new", XS_Gdk__Texture_new);
        newXS_deffile("G::Object::bind_property_full", XS_G__Object_bind_property_full);
        newXS_deffile("G::Object::connect", XS_G__Object_connect);
        newXS_deffile("G::Object::DESTROY", XS_G__Object_DESTROY);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

#ifdef __cplusplus
}
#endif
