typedef pcap_if_t *PCAP__If;
typedef pcap_t *PCAP__Handle;
typedef UDPPacketInfo *PCAP__Packet;
typedef struct bpf_program *PCAP__Program;
typedef struct pcap_pkthdr *PCAP__Header;
typedef int *Constants;
typedef Constants Gtk__Win__Constants;

typedef GtkApplication *Gtk__Application;
typedef GApplication *Gio__Application;
typedef GtkBox *Gtk__Box;
typedef GtkWindow *Gtk__Window;
typedef GtkApplicationWindow *Gtk__ApplicationWindow;
typedef GtkOverlay *Gtk__Overlay;
typedef GObject *G__Object;
typedef GtkWidget *Gtk__Widget;
typedef GtkButton *Gtk__Button;
typedef GtkCheckButton *Gtk__CheckButton;
typedef GtkEntry *Gtk__Entry;
typedef GtkPicture *Gtk__Picture;
typedef GFile *Gio__File;
typedef GdkTexture *Gdk__Texture;
typedef GdkDisplay *Gdk__Display;
typedef GtkCssProvider *Gtk__CssProvider;
typedef GtkGrid *Gtk__Grid;
typedef GtkLabel *Gtk__Label;
