package Gtk::Dropdown;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package Gtk::Picture;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package Gtk::Overlay;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package Gtk::Entry;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget Gtk::Editable/;
package Gdk::Display;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/G::Object/;
package Gtk::Box;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package Gtk::Window;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package Gtk::CheckButton;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package Gtk::AlertDialog;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/G::Object/;
package Gio::Application;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/G::Object/;
package Gtk::Grid;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package Gdk::Texture;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/G::Object/;
package Gtk::ApplicationWindow;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Window/;
package Gtk::Application;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gio::Application/;
package Gtk::ScrolledWindow;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package G::File;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/G::Object/;
package Gtk::Button;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package Gtk::CssProvider;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/G::Object/;
package Gtk::Label;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/Gtk::Widget/;
package Gtk::Widget;
use v5.38.0;
use vars qw/@ISA/;
our @ISA = qw/G::Object/;
